-- Query: https://dune.com/queries/8798422
-- Matview: dune.paltalabs.result_scf_phoenix_activity_archive   cron: 0 3 * * 1
-- Última ejecución: 01M32TCDARCHZNEMXQV0ED4EE0
-- Costo: 331.779 cr; filas: 262058; engine medium
-- Generated by scripts/activity_sql.py. Archive, incremental: previous snapshot of this matview
-- plus, on the first Monday of the month only, the month that just closed.
WITH prev AS (SELECT * FROM dune.paltalabs.result_scf_phoenix_activity_archive WHERE row_kind = 'activity'),
src AS (
WITH pools AS (SELECT * FROM (VALUES
    ('CBHCRSVX3ZZ7EGTSYMKPEFGZNWRVCSESQR3UABET4MIW52N4EVU6BIZX', 'CAS3J7GYLGXMF6TDJBBYYSE3HQ6BBSMLNUQ34T6TZMYMW2EVH34XOWMA', 'CCW67TSZV3SSS2HXMBQ5JFGCKJNXKZM7UQUWUZPUTHXSTZLEO7SJMI75'),
    ('CBCZGGNOEUZG4CAAE7TGTQQHETZMKUT4OIPFHHPKEUX46U4KXBBZ3GLH', 'CAS3J7GYLGXMF6TDJBBYYSE3HQ6BBSMLNUQ34T6TZMYMW2EVH34XOWMA', 'CBZ7M5B3Y4WWBZ5XK5UZCAFOEZ23KSSZXYECYX3IXM6E2JOLQC52DK32'),
    ('CAZ6W4WHVGQBGURYTUOLCUOOHW6VQGAAPSPCD72VEDZMBBPY7H43AYEC', 'CBZ7M5B3Y4WWBZ5XK5UZCAFOEZ23KSSZXYECYX3IXM6E2JOLQC52DK32', 'CCW67TSZV3SSS2HXMBQ5JFGCKJNXKZM7UQUWUZPUTHXSTZLEO7SJMI75'),
    ('CBISULYO5ZGS32WTNCBMEFCNKNSLFXCQ4Z3XHVDP4X4FLPSEALGSY3PS', 'CAS3J7GYLGXMF6TDJBBYYSE3HQ6BBSMLNUQ34T6TZMYMW2EVH34XOWMA', 'CDTKPWPLOURQA2SGTKTUQOWRCBZEORB4BWBOMJ3D3ZTQQSGE5F6JBQLV'),
    ('CDQLKNH3725BUP4HPKQKMM7OO62FDVXVTO7RCYPID527MZHJG2F3QBJW', 'CCW67TSZV3SSS2HXMBQ5JFGCKJNXKZM7UQUWUZPUTHXSTZLEO7SJMI75', 'CDHNIO6IJ7EBFUDVALSE347YYNV3RKFB3Y5NZ3W4RH4QP4IS56MGSI5E'),
    ('CBW5G5SO5SDYUGQVU7RMZ2KJ34POM3AMODOBIV2RQYG4KJDUUBVC3P2T', 'CCW67TSZV3SSS2HXMBQ5JFGCKJNXKZM7UQUWUZPUTHXSTZLEO7SJMI75', 'CDOZE45WZ67M6DNO577SKX3AG6N3I3Y6HZNA63APVYEAF2X6Q6P6V5G6'),
    ('CDMXKSLG5GITGFYERUW2MRYOBUQCMRT2QE5Y4PU3QZ53EBFWUXAXUTBC', 'CAS3J7GYLGXMF6TDJBBYYSE3HQ6BBSMLNUQ34T6TZMYMW2EVH34XOWMA', 'CDIKURWHYS4FFTR5KOQK6MBFZA2K3E26WGBQI6PXBYWZ4XIOPJHDFJKP'),
    ('CD5XNKK3B6BEF2N7ULNHHGAMOKZ7P6456BFNIHRF4WNTEDKBRWAE7IAA', 'CBZ7M5B3Y4WWBZ5XK5UZCAFOEZ23KSSZXYECYX3IXM6E2JOLQC52DK32', 'CCW67TSZV3SSS2HXMBQ5JFGCKJNXKZM7UQUWUZPUTHXSTZLEO7SJMI75'),
    ('CC6MJZN3HFOJKXN42ANTSCLRFOMHLFXHWPNAX64DQNUEBDMUYMPHASAV', 'CBN3NCJSMOQTC6SPEYK3A44NU4VS3IPKTARJLI3Y77OH27EWBY36TP7U', 'CCW67TSZV3SSS2HXMBQ5JFGCKJNXKZM7UQUWUZPUTHXSTZLEO7SJMI75'),
    ('CB5QUVK5GS3IU23TMFZQ3P5J24YBBZP5PHUQAEJ2SP5K55PFTJRUQG2L', 'CAS3J7GYLGXMF6TDJBBYYSE3HQ6BBSMLNUQ34T6TZMYMW2EVH34XOWMA', 'CBN3NCJSMOQTC6SPEYK3A44NU4VS3IPKTARJLI3Y77OH27EWBY36TP7U'),
    ('CCKOC2LJTPDBKDHTL3M5UO7HFZ2WFIHSOKCELMKQP3TLCIVUBKOQL4HB', 'CAS3J7GYLGXMF6TDJBBYYSE3HQ6BBSMLNUQ34T6TZMYMW2EVH34XOWMA', 'CBCO65UOWXY2GR66GOCMCN6IU3Y45TXCPBY3FLUNL4AOUMOCKVIVV6JC'),
    ('CCUCE5H5CKW3S7JBESGCES6ZGDMWLNRY3HOFET3OH33MXZWKXNJTKSM3', 'CBCO65UOWXY2GR66GOCMCN6IU3Y45TXCPBY3FLUNL4AOUMOCKVIVV6JC', 'CCW67TSZV3SSS2HXMBQ5JFGCKJNXKZM7UQUWUZPUTHXSTZLEO7SJMI75'),
    ('CBENABXP6C4C7WG6KB7JQOTDS5GIIXF3IX3PIYNZFCDZDWUHITO2HZ4S', 'CAS3J7GYLGXMF6TDJBBYYSE3HQ6BBSMLNUQ34T6TZMYMW2EVH34XOWMA', 'CCW67TSZV3SSS2HXMBQ5JFGCKJNXKZM7UQUWUZPUTHXSTZLEO7SJMI75'),
    ('CCPPPTDWJIWXQUQ2CN64S5JYQ7GYWVZIT7YWUUTH75HKIZX53Z2CE3XI', 'CBZ7M5B3Y4WWBZ5XK5UZCAFOEZ23KSSZXYECYX3IXM6E2JOLQC52DK32', 'CCW67TSZV3SSS2HXMBQ5JFGCKJNXKZM7UQUWUZPUTHXSTZLEO7SJMI75')) AS v(pool, token_a, token_b)),
ev AS (
  SELECT DISTINCT
    he.contract_id AS pool, he.closed_at, lower(to_hex(he.transaction_hash)) AS tx_hash,
    COALESCE(json_extract_scalar(he.topics_decoded, '$[0].string'), json_extract_scalar(he.topics_decoded, '$[0].symbol')) AS action,
    json_extract_scalar(he.topics_decoded, '$[1].string') AS field,
    he.data_decoded
  FROM stellar.history_contract_events he
  WHERE he.closed_at_date >= CURRENT_DATE - INTERVAL '75' DAY AND he.closed_at_date >= (SELECT MAX(covered_until) FROM dune.paltalabs.result_scf_phoenix_activity_archive WHERE row_kind = 'metadata') AND he.closed_at_date < CAST(date_trunc('month', CURRENT_DATE) AS DATE) AND day_of_month(CURRENT_DATE) <= 7
    AND he.contract_id IN ('CBHCRSVX3ZZ7EGTSYMKPEFGZNWRVCSESQR3UABET4MIW52N4EVU6BIZX', 'CBCZGGNOEUZG4CAAE7TGTQQHETZMKUT4OIPFHHPKEUX46U4KXBBZ3GLH', 'CAZ6W4WHVGQBGURYTUOLCUOOHW6VQGAAPSPCD72VEDZMBBPY7H43AYEC', 'CBISULYO5ZGS32WTNCBMEFCNKNSLFXCQ4Z3XHVDP4X4FLPSEALGSY3PS', 'CDQLKNH3725BUP4HPKQKMM7OO62FDVXVTO7RCYPID527MZHJG2F3QBJW', 'CBW5G5SO5SDYUGQVU7RMZ2KJ34POM3AMODOBIV2RQYG4KJDUUBVC3P2T', 'CDMXKSLG5GITGFYERUW2MRYOBUQCMRT2QE5Y4PU3QZ53EBFWUXAXUTBC', 'CD5XNKK3B6BEF2N7ULNHHGAMOKZ7P6456BFNIHRF4WNTEDKBRWAE7IAA', 'CC6MJZN3HFOJKXN42ANTSCLRFOMHLFXHWPNAX64DQNUEBDMUYMPHASAV', 'CB5QUVK5GS3IU23TMFZQ3P5J24YBBZP5PHUQAEJ2SP5K55PFTJRUQG2L', 'CCKOC2LJTPDBKDHTL3M5UO7HFZ2WFIHSOKCELMKQP3TLCIVUBKOQL4HB', 'CCUCE5H5CKW3S7JBESGCES6ZGDMWLNRY3HOFET3OH33MXZWKXNJTKSM3', 'CBENABXP6C4C7WG6KB7JQOTDS5GIIXF3IX3PIYNZFCDZDWUHITO2HZ4S', 'CCPPPTDWJIWXQUQ2CN64S5JYQ7GYWVZIT7YWUUTH75HKIZX53Z2CE3XI')
    AND he.type_string = 'ContractEventTypeContract'
    AND he.successful = TRUE AND he.in_successful_contract_call = TRUE
    AND COALESCE(json_extract_scalar(he.topics_decoded, '$[0].string'), json_extract_scalar(he.topics_decoded, '$[0].symbol'))
        IN ('swap', 'provide_liquidity', 'withdraw_liquidity')
),
legacy AS (
  SELECT pool, closed_at, tx_hash, action, CAST(NULL AS VARBINARY) AS event_key,
         replace(replace(field, ' ', '_'), '-', '_') AS k,
         json_extract_scalar(data_decoded, '$.address') AS v_addr,
         TRY(CAST(json_extract_scalar(data_decoded, '$.i128') AS DECIMAL(38,0))) AS v_i128
  FROM ev WHERE field IS NOT NULL
),
modern AS (
  SELECT e.pool, e.closed_at, e.tx_hash, e.action, xxhash64(to_utf8(e.data_decoded)) AS event_key,
         replace(replace(json_extract_scalar(elem, '$.key.symbol'), ' ', '_'), '-', '_') AS k,
         json_extract_scalar(elem, '$.val.address') AS v_addr,
         TRY(CAST(json_extract_scalar(elem, '$.val.i128') AS DECIMAL(38,0))) AS v_i128
  FROM ev e
  CROSS JOIN UNNEST(CAST(json_extract(e.data_decoded, '$.map') AS array(json))) AS t(elem)
  WHERE e.field IS NULL AND e.data_decoded LIKE '{"map":%'
),
kv AS (SELECT * FROM legacy UNION ALL SELECT * FROM modern),
pivoted AS (
  SELECT pool, tx_hash, action, event_key, MIN(closed_at) AS closed_at,
    COUNT(DISTINCT CASE WHEN k = 'sender' THEN v_addr END) AS senders,
    MAX(CASE WHEN k = 'sender' THEN v_addr END) AS sender,
    MAX(CASE WHEN k = 'sell_token' THEN v_addr END) AS sell_token,
    MAX(CASE WHEN k = 'buy_token' THEN v_addr END) AS buy_token,
    MAX(CASE WHEN k = 'token_a' THEN v_addr END) AS token_a,
    MAX(CASE WHEN k = 'token_b' THEN v_addr END) AS token_b,
    SUM(CASE WHEN k = 'offer_amount' THEN v_i128 END) AS offer_amount,
    SUM(CASE WHEN k = 'return_amount' THEN v_i128 END) AS return_amount,
    SUM(CASE WHEN k = 'token_a_amount' THEN v_i128 END) AS token_a_amount,
    SUM(CASE WHEN k = 'token_b_amount' THEN v_i128 END) AS token_b_amount,
    SUM(CASE WHEN k = 'return_amount_a' THEN v_i128 END) AS return_amount_a,
    SUM(CASE WHEN k = 'return_amount_b' THEN v_i128 END) AS return_amount_b
  FROM kv
  GROUP BY 1, 2, 3, 4
)
SELECT 'phoenix' AS protocol, p.pool AS contract_id, p.closed_at, p.tx_hash, p.sender AS user_address, p.action,
  CASE p.action WHEN 'swap' THEN 'swapper' ELSE 'lp' END AS role, p.pool,
  CASE p.action WHEN 'swap' THEN p.sell_token ELSE COALESCE(p.token_a, r.token_a) END AS token_a,
  CAST(CASE p.action WHEN 'swap' THEN p.offer_amount WHEN 'provide_liquidity' THEN p.token_a_amount ELSE p.return_amount_a END * DECIMAL '0.0000001' AS DECIMAL(38,7)) AS amount_a,
  CASE p.action WHEN 'swap' THEN p.buy_token ELSE COALESCE(p.token_b, r.token_b) END AS token_b,
  CAST(CASE p.action WHEN 'swap' THEN p.return_amount WHEN 'provide_liquidity' THEN p.token_b_amount ELSE p.return_amount_b END * DECIMAL '0.0000001' AS DECIMAL(38,7)) AS amount_b
FROM pivoted p LEFT JOIN pools r ON r.pool = p.pool
WHERE p.senders = 1
UNION ALL
SELECT DISTINCT 'phoenix', l.pool, l.closed_at, l.tx_hash, l.v_addr, l.action,
  CASE l.action WHEN 'swap' THEN 'swapper' ELSE 'lp' END, l.pool, NULL, CAST(NULL AS DECIMAL(38,7)), NULL, CAST(NULL AS DECIMAL(38,7))
FROM legacy l JOIN pivoted p ON p.pool = l.pool AND p.tx_hash = l.tx_hash AND p.action = l.action AND p.event_key IS NULL
WHERE p.senders > 1 AND l.k = 'sender'
)
SELECT protocol, contract_id, closed_at, tx_hash, user_address, action, role, pool, token_a, amount_a, token_b, amount_b,
       'activity' AS row_kind, covered_from, CASE WHEN day_of_month(CURRENT_DATE) <= 7 THEN GREATEST((SELECT MAX(covered_until) FROM dune.paltalabs.result_scf_phoenix_activity_archive WHERE row_kind = 'metadata'), CAST(date_trunc('month', CURRENT_DATE) AS DATE)) ELSE (SELECT MAX(covered_until) FROM dune.paltalabs.result_scf_phoenix_activity_archive WHERE row_kind = 'metadata') END AS covered_until, refreshed_at, source_layer
FROM prev
UNION ALL
SELECT protocol, contract_id, closed_at, tx_hash, user_address, action, role, pool, token_a, amount_a, token_b, amount_b,
       'activity', DATE '2024-02-01', CASE WHEN day_of_month(CURRENT_DATE) <= 7 THEN GREATEST((SELECT MAX(covered_until) FROM dune.paltalabs.result_scf_phoenix_activity_archive WHERE row_kind = 'metadata'), CAST(date_trunc('month', CURRENT_DATE) AS DATE)) ELSE (SELECT MAX(covered_until) FROM dune.paltalabs.result_scf_phoenix_activity_archive WHERE row_kind = 'metadata') END, CURRENT_TIMESTAMP, 'archive'
FROM src
WHERE regexp_like(user_address, '^[GC][A-Z2-7]{55}$') AND role IS NOT NULL
UNION ALL
SELECT 'phoenix', NULL, CAST(NULL AS TIMESTAMP WITH TIME ZONE), NULL, NULL, NULL, NULL, NULL, NULL, CAST(NULL AS DECIMAL(38,7)), NULL, CAST(NULL AS DECIMAL(38,7)),
       'metadata', DATE '2024-02-01', CASE WHEN day_of_month(CURRENT_DATE) <= 7 THEN GREATEST((SELECT MAX(covered_until) FROM dune.paltalabs.result_scf_phoenix_activity_archive WHERE row_kind = 'metadata'), CAST(date_trunc('month', CURRENT_DATE) AS DATE)) ELSE (SELECT MAX(covered_until) FROM dune.paltalabs.result_scf_phoenix_activity_archive WHERE row_kind = 'metadata') END, CURRENT_TIMESTAMP, 'archive'
