-- Query: https://dune.com/queries/8798419
-- Matview: dune.paltalabs.result_scf_fxdao_activity_archive   cron: 0 3 * * 1
-- Última ejecución: 01M32WD2QSF7NW16BPA6HKTWVT
-- Costo: 1.166 cr; filas: 3786; engine medium
-- Generated by scripts/activity_sql.py. Archive, incremental: previous snapshot of this matview
-- plus, on the first Monday of the month only, the month that just closed.
WITH prev AS (SELECT * FROM dune.paltalabs.result_scf_fxdao_activity_archive WHERE row_kind = 'activity'),
src AS (
WITH ops AS (
  SELECT o.contract_id, o.closed_at, o.transaction_id, o.source_account,
         json_extract_scalar(o.parameters_json_decoded, '$[1].symbol') AS fn,
         o.parameters_json_decoded AS params
  FROM stellar.history_operations o
  WHERE o.closed_at_date >= CURRENT_DATE - INTERVAL '75' DAY AND o.closed_at_date >= (SELECT MAX(covered_until) FROM dune.paltalabs.result_scf_fxdao_activity_archive WHERE row_kind = 'metadata') AND o.closed_at_date < CAST(date_trunc('month', CURRENT_DATE) AS DATE) AND day_of_month(CURRENT_DATE) <= 7
    AND o.type_string = 'invoke_host_function'
    AND o.contract_id IN ('CCUN4RXU5VNDHSF4S4RKV4ZJYMX2YWKOH6L4AKEKVNVDQ7HY5QIAO4UB', 'CDCART6WRSM2K4CKOAOB5YKUVBSJ6KLOVS7ZEJHA4OAQ2FXX7JOHLXIP')
),
tx AS (
  SELECT id, lower(to_hex(transaction_hash)) AS tx_hash
  FROM stellar.history_transactions
  WHERE closed_at_date >= CURRENT_DATE - INTERVAL '75' DAY AND closed_at_date >= (SELECT MAX(covered_until) FROM dune.paltalabs.result_scf_fxdao_activity_archive WHERE row_kind = 'metadata') AND closed_at_date < CAST(date_trunc('month', CURRENT_DATE) AS DATE) AND day_of_month(CURRENT_DATE) <= 7 AND successful = TRUE
)
SELECT 'fxdao' AS protocol, o.contract_id, o.closed_at, t.tx_hash, o.source_account AS user_address,
  CASE WHEN o.contract_id = 'CDCART6WRSM2K4CKOAOB5YKUVBSJ6KLOVS7ZEJHA4OAQ2FXX7JOHLXIP' THEN 'locking_' || o.fn ELSE o.fn END AS action,
  CASE
    WHEN o.contract_id = 'CDCART6WRSM2K4CKOAOB5YKUVBSJ6KLOVS7ZEJHA4OAQ2FXX7JOHLXIP' THEN 'lp'
    WHEN o.fn IN ('new_vault', 'increase_collateral', 'increase_debt', 'pay_debt', 'withdraw_collateral') THEN 'vault_owner'
    WHEN o.fn = 'redeem' THEN 'redeemer'
    WHEN o.fn IN ('liquidate', 'evict') THEN 'liquidator'
  END AS role,
  CAST(NULL AS VARCHAR) AS pool,
  regexp_extract(o.params, '"denomination"\},"val":\{"symbol":"([A-Z]+)"', 1) AS token_a,
  CAST(CASE WHEN o.contract_id = 'CDCART6WRSM2K4CKOAOB5YKUVBSJ6KLOVS7ZEJHA4OAQ2FXX7JOHLXIP' AND o.fn = 'deposit'
            THEN TRY(CAST(json_extract_scalar(o.params, '$[4].u128') AS DECIMAL(38,0))) * DECIMAL '0.0000001' END AS DECIMAL(38,7)) AS amount_a,
  CAST(NULL AS VARCHAR) AS token_b, CAST(NULL AS DECIMAL(38,7)) AS amount_b
FROM ops o JOIN tx t ON t.id = o.transaction_id
WHERE (o.contract_id = 'CDCART6WRSM2K4CKOAOB5YKUVBSJ6KLOVS7ZEJHA4OAQ2FXX7JOHLXIP' AND o.fn IN ('deposit', 'withdraw'))
   OR (o.contract_id = 'CCUN4RXU5VNDHSF4S4RKV4ZJYMX2YWKOH6L4AKEKVNVDQ7HY5QIAO4UB' AND o.fn IN ('new_vault', 'increase_collateral', 'increase_debt', 'pay_debt', 'withdraw_collateral', 'redeem', 'liquidate', 'evict'))
)
SELECT protocol, contract_id, closed_at, tx_hash, user_address, action, role, pool, token_a, amount_a, token_b, amount_b,
       'activity' AS row_kind, covered_from, CASE WHEN day_of_month(CURRENT_DATE) <= 7 THEN GREATEST((SELECT MAX(covered_until) FROM dune.paltalabs.result_scf_fxdao_activity_archive WHERE row_kind = 'metadata'), CAST(date_trunc('month', CURRENT_DATE) AS DATE)) ELSE (SELECT MAX(covered_until) FROM dune.paltalabs.result_scf_fxdao_activity_archive WHERE row_kind = 'metadata') END AS covered_until, refreshed_at, source_layer
FROM prev
UNION ALL
SELECT protocol, contract_id, closed_at, tx_hash, user_address, action, role, pool, token_a, amount_a, token_b, amount_b,
       'activity', DATE '2024-02-01', CASE WHEN day_of_month(CURRENT_DATE) <= 7 THEN GREATEST((SELECT MAX(covered_until) FROM dune.paltalabs.result_scf_fxdao_activity_archive WHERE row_kind = 'metadata'), CAST(date_trunc('month', CURRENT_DATE) AS DATE)) ELSE (SELECT MAX(covered_until) FROM dune.paltalabs.result_scf_fxdao_activity_archive WHERE row_kind = 'metadata') END, CURRENT_TIMESTAMP, 'archive'
FROM src
WHERE regexp_like(user_address, '^[GC][A-Z2-7]{55}$') AND role IS NOT NULL
UNION ALL
SELECT 'fxdao', NULL, CAST(NULL AS TIMESTAMP WITH TIME ZONE), NULL, NULL, NULL, NULL, NULL, NULL, CAST(NULL AS DECIMAL(38,7)), NULL, CAST(NULL AS DECIMAL(38,7)),
       'metadata', DATE '2024-02-01', CASE WHEN day_of_month(CURRENT_DATE) <= 7 THEN GREATEST((SELECT MAX(covered_until) FROM dune.paltalabs.result_scf_fxdao_activity_archive WHERE row_kind = 'metadata'), CAST(date_trunc('month', CURRENT_DATE) AS DATE)) ELSE (SELECT MAX(covered_until) FROM dune.paltalabs.result_scf_fxdao_activity_archive WHERE row_kind = 'metadata') END, CURRENT_TIMESTAMP, 'archive'
