#!/usr/bin/env python3
"""Baja el SQL de cada query listada en queries.yml y lo escribe en queries/<protocolo>/<id>_<slug>.sql.

Uso:
    DUNE_API_KEY=... python3 scripts/mirror.py            # todas
    DUNE_API_KEY=... python3 scripts/mirror.py 8666478    # una

La llave es la del team paltalabs en Dune (Settings > API). Sin llave el script no hace nada
destructivo: falla antes de tocar archivos. Los .sql generados no se editan a mano: el SQL
vive en Dune, la metadata en queries.yml, y este script junta las dos cosas.
"""
import json
import os
import sys
import urllib.request
from pathlib import Path

try:
    import yaml
except ImportError:
    yaml = None

ROOT = Path(__file__).resolve().parent.parent
REGISTRY = ROOT / "queries.yml"


def load_registry():
    text = REGISTRY.read_text()
    if yaml:
        return yaml.safe_load(text)
    raise SystemExit("falta pyyaml: pip install pyyaml")


def fetch(query_id, key):
    req = urllib.request.Request(
        f"https://api.dune.com/api/v1/query/{query_id}",
        headers={"X-DUNE-API-KEY": key},
    )
    with urllib.request.urlopen(req, timeout=60) as r:
        return json.load(r)


def header(q, remote):
    m = q.get("measured") or {}
    lines = [
        f"-- Query: {remote.get('name')}          https://dune.com/queries/{q['id']}",
        f"-- Matview: {q.get('matview') or 'ninguna'}   cron: {q.get('cron') or 'ninguno'}",
        f"-- Lee: {', '.join(q.get('reads', []))}",
    ]
    if m:
        lines.append(
            f"-- Costo medido: {m.get('date')} {m.get('credits')} cr, {m.get('rows')} filas, "
            f"engine medium, ventana {m.get('window', 'completa')}"
        )
    if q.get("note"):
        lines.append(f"-- Notas: {q['note']}")
    lines.append("-- Generated by scripts/mirror.py from queries.yml. Do not edit: the SQL lives in Dune.")
    return "\n".join(lines) + "\n\n"


def main():
    key = os.environ.get("DUNE_API_KEY")
    if not key:
        raise SystemExit("DUNE_API_KEY no está en el entorno")
    only = {int(a) for a in sys.argv[1:]}
    reg = load_registry()
    for q in reg["queries"]:
        if only and q["id"] not in only:
            continue
        remote = fetch(q["id"], key)
        sql = remote.get("query_sql") or remote.get("sql") or ""
        if not sql.strip():
            print(f"{q['id']}: sin SQL en la respuesta, se salta", file=sys.stderr)
            continue
        out = ROOT / "queries" / q["protocol"] / f"{q['id']}_{q['slug']}.sql"
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(header(q, remote) + sql.rstrip() + "\n")
        print(f"{q['id']} -> {out.relative_to(ROOT)}  ({len(sql)} chars)")


if __name__ == "__main__":
    main()
