-- Query: https://dune.com/queries/8798463
-- Matview: dune.paltalabs.result_scf_blend_activity_archive   cron: 0 3 * * 1
-- Última ejecución: 01M32TK1QKPC17YFG5RWEXACZ2
-- Costo: 87.826 cr; filas: 1204167; engine medium
-- Generated by scripts/activity_sql.py. Archive, incremental: previous snapshot of this matview
-- plus, on the first Monday of the month only, the month that just closed.
WITH prev AS (SELECT * FROM dune.paltalabs.result_scf_blend_activity_archive WHERE row_kind = 'activity'),
src AS (
WITH ev AS (
  SELECT DISTINCT
    CASE WHEN he.contract_id IN ('CAO3AGAMZVRMHITL36EJ2VZQWKYRPWMQAPDQD5YEOF3GIF7T44U4JAL3', 'CAQQR5SWBXKIGZKPBZDH3KM5GQ5GUTPKB7JAFCINLZBC5WXPJKRG3IM7') THEN 'backstop' ELSE 'pool' END AS kind,
    he.contract_id, he.closed_at, lower(to_hex(he.transaction_hash)) AS tx_hash, he.topics_decoded, he.data_decoded
  FROM stellar.history_contract_events he
  WHERE he.closed_at_date >= CURRENT_DATE - INTERVAL '75' DAY AND he.closed_at_date >= (SELECT MAX(covered_until) FROM dune.paltalabs.result_scf_blend_activity_archive WHERE row_kind = 'metadata') AND he.closed_at_date < CAST(date_trunc('month', CURRENT_DATE) AS DATE) AND day_of_month(CURRENT_DATE) <= 7
    AND he.contract_id IN ('CDVQVKOY2YSXS2IC7KN6MNASSHPAO7UN2UR2ON4OI2SKMFJNVAMDX6DP', 'CBP7NO6F7FRDHSOFQBT2L2UWYIZ2PU76JKVRYAQTG3KZSQLYAOKIF2WB', 'CDU4RTOYFZERUD727WW6VRXH5IK35GLCXCPK5ILUYRLLYYMTYSCJXUEA', 'CCTZXMW3DJIKDI3UVDUJR6PM4WFFEB5RIWDXJBGIEFBD5XFHI26LZ5BU', 'CBVOPI6QC6OWVCOEZDCFELAGQNAOHUS4CWOKAVADKQZXVSWR2R5IAKO7', 'CADP6E57HEJOAWHBSTEDJYFJSRU5C5D7YBHFEET23CAHD2KGD4XKCFMS', 'CB22FIF722FWWHKDX6URY2LHTOS6TWLPXL2IOGY5QS6YNQXTRBDCNPD3', 'CDL3EQ4P3DQH5Q6BT3AINZCCJKUHSXPJAOF7YP3JE7MFJX7FGXHPT27B', 'CDJ6Q3A2NUK3ANWFGXCHUBPQJXKAXBHNUVILGTEOTSEH2NDZC4FI632B', 'CDAKUFO3WOUG2DLY6XTNRKBSK53VJTJXMTOUEMPKOWN4R756OFICXWID', 'CDIUMS2ZNGNGHDRBKFXS4QU23ATPYCTDBUHGZ6FS2MPAEY37FAC4JD3R', 'CB7V7T52OLKMBC5QPL7GH2OKR4XV6YWDURUXSAAAFCPSNX7EPBYF5DJE', 'CDK4KXOYG332TO7VDARUJ66RMQTEADFSZY3RDJZQBS7ZFCD25RV52NXP', 'CDE65QK2ROZ32V2LVLBOKYPX47TYMYO37Z6ASQTBRTBNK53C7C6QF4Y7', 'CDJD2PFCHD2R4SHP3WJ4C6JEF445ODSO74WOCKNFS25I4XI7HMLK3VYO', 'CAJJZSGMMM3PD7N33TAPHGBUGTB43OC73HVIK2L2G6BNGGGYOSSYBXBD', 'CBNR7PYFY775UG7W37B4OJG2OBBUKLFW6VIBHFDKKLR2HECPRMRZMDK3', 'CCCCIQSDILITHMM7PBSLVDT5MISSY7R26MNZXCX4H7J5JQ5FPIYOGYFS', 'CB4OFHAY2TAEYUVPOJS36S657C6NYMSIFUNCCA5AHYT46Y5XUID3O2ED', 'CAE7QVOMBLZ53CDRGK3UNRRHG5EZ5NQA7HHTFASEMYBWHG6MDFZTYHXC', 'CBYOBT7ZCCLQCBUYYIABZLSEGDPEUWXCUXQTZYOG3YBDR7U357D5ZIRF', 'CALRF5I2OCJCU577R6MZBCY5IIXNMAAG6PNMN7GUKEYIXBJCJN2FJRVI', 'CADR6Q2UOCDJAGXMAB2E6SRT35STLZ2IGLZUCXJQG7TC2LNKCU5RTQVY', 'CDMAVJPFXPADND3YRL4BSM3AKZWCTFMX27GLLXCML3PD62HEQS5FPVAI', 'CDZVHCO7LDUJZSME3PJPJXAKT7F6W5IXSOXTJ2QEK3Y2X2CDUREBUMUY', 'CC4HHXPKR3FIXUQEC53MAK2IVWD6APAEBBXP5XCIW5FISN6PQOAC6UXG', 'CAIYBZSBI6XXI3W7EDXDRWLUBK3RCAPHTK4DNX74DZGWE53KYWBHE236', 'CAO3AGAMZVRMHITL36EJ2VZQWKYRPWMQAPDQD5YEOF3GIF7T44U4JAL3', 'CAQQR5SWBXKIGZKPBZDH3KM5GQ5GUTPKB7JAFCINLZBC5WXPJKRG3IM7')
    AND he.type_string = 'ContractEventTypeContract'
    AND he.successful = TRUE AND he.in_successful_contract_call = TRUE
),
parsed AS (
  SELECT kind, contract_id, closed_at, tx_hash,
    json_extract_scalar(topics_decoded, '$[0].symbol')  AS action,
    json_extract_scalar(topics_decoded, '$[1].address') AS t1_addr,
    json_extract_scalar(topics_decoded, '$[2].address') AS t2_addr,
    json_extract_scalar(data_decoded, '$.vec[0].address') AS d0_addr,
    COALESCE(
      TRY(CAST(COALESCE(json_extract_scalar(data_decoded, '$.vec[0].i128'), json_extract_scalar(data_decoded, '$.i128')) AS DECIMAL(38,0))),
      TRY(CAST(json_extract_scalar(data_decoded, '$.vec[0].i128.hi') AS DECIMAL(38,0)) * DECIMAL '18446744073709551616'
          + CAST(json_extract_scalar(data_decoded, '$.vec[0].i128.lo') AS DECIMAL(38,0)))
    ) AS d0_i128
  FROM ev
)
SELECT 'blend' AS protocol, contract_id, closed_at, tx_hash,
  CASE
    WHEN kind = 'pool' AND action = 'fill_auction' THEN d0_addr
    WHEN action = 'claim' THEN t1_addr
    ELSE t2_addr
  END AS user_address,
  CASE WHEN kind = 'backstop' THEN 'backstop_' || action ELSE action END AS action,
  CASE
    WHEN kind = 'pool' AND action IN ('supply', 'withdraw', 'supply_collateral', 'withdraw_collateral') THEN 'lender'
    WHEN kind = 'pool' AND action IN ('borrow', 'repay', 'flash_loan') THEN 'borrower'
    WHEN kind = 'pool' AND action = 'fill_auction' THEN 'liquidator'
    WHEN action = 'claim' THEN 'claimer'
    ELSE 'backstop_provider'
  END AS role,
  CASE WHEN kind = 'backstop' THEN t1_addr ELSE contract_id END AS pool,
  CASE
    WHEN kind = 'pool' AND action IN ('supply', 'withdraw', 'supply_collateral', 'withdraw_collateral', 'borrow', 'repay', 'flash_loan') THEN t1_addr
    WHEN kind = 'backstop' AND action IN ('deposit', 'withdraw', 'donate') THEN 'CAS3FL6TLZKDGGSISDBWGGPXT3NRR4DYTZD7YOD3HMYO6LTJUVGRVEAM'
  END AS token_a,
  CASE
    WHEN (kind = 'pool' AND action IN ('supply', 'withdraw', 'supply_collateral', 'withdraw_collateral', 'borrow', 'repay', 'flash_loan'))
      OR (kind = 'backstop' AND action IN ('deposit', 'withdraw', 'donate'))
    THEN CAST(d0_i128 * DECIMAL '0.0000001' AS DECIMAL(38,7))
  END AS amount_a,
  CAST(NULL AS VARCHAR) AS token_b, CAST(NULL AS DECIMAL(38,7)) AS amount_b
FROM parsed
WHERE (kind = 'pool' AND action IN ('supply', 'withdraw', 'supply_collateral', 'withdraw_collateral', 'borrow', 'repay', 'flash_loan', 'fill_auction', 'claim'))
   OR (kind = 'backstop' AND action IN ('deposit', 'withdraw', 'queue_withdrawal', 'dequeue_withdrawal', 'donate', 'claim'))
)
SELECT protocol, contract_id, closed_at, tx_hash, user_address, action, role, pool, token_a, amount_a, token_b, amount_b,
       'activity' AS row_kind, covered_from, CASE WHEN day_of_month(CURRENT_DATE) <= 7 THEN GREATEST((SELECT MAX(covered_until) FROM dune.paltalabs.result_scf_blend_activity_archive WHERE row_kind = 'metadata'), CAST(date_trunc('month', CURRENT_DATE) AS DATE)) ELSE (SELECT MAX(covered_until) FROM dune.paltalabs.result_scf_blend_activity_archive WHERE row_kind = 'metadata') END AS covered_until, refreshed_at, source_layer
FROM prev
UNION ALL
SELECT protocol, contract_id, closed_at, tx_hash, user_address, action, role, pool, token_a, amount_a, token_b, amount_b,
       'activity', DATE '2024-02-01', CASE WHEN day_of_month(CURRENT_DATE) <= 7 THEN GREATEST((SELECT MAX(covered_until) FROM dune.paltalabs.result_scf_blend_activity_archive WHERE row_kind = 'metadata'), CAST(date_trunc('month', CURRENT_DATE) AS DATE)) ELSE (SELECT MAX(covered_until) FROM dune.paltalabs.result_scf_blend_activity_archive WHERE row_kind = 'metadata') END, CURRENT_TIMESTAMP, 'archive'
FROM src
WHERE regexp_like(user_address, '^[GC][A-Z2-7]{55}$') AND role IS NOT NULL
UNION ALL
SELECT 'blend', NULL, CAST(NULL AS TIMESTAMP WITH TIME ZONE), NULL, NULL, NULL, NULL, NULL, NULL, CAST(NULL AS DECIMAL(38,7)), NULL, CAST(NULL AS DECIMAL(38,7)),
       'metadata', DATE '2024-02-01', CASE WHEN day_of_month(CURRENT_DATE) <= 7 THEN GREATEST((SELECT MAX(covered_until) FROM dune.paltalabs.result_scf_blend_activity_archive WHERE row_kind = 'metadata'), CAST(date_trunc('month', CURRENT_DATE) AS DATE)) ELSE (SELECT MAX(covered_until) FROM dune.paltalabs.result_scf_blend_activity_archive WHERE row_kind = 'metadata') END, CURRENT_TIMESTAMP, 'archive'
