-- Query: https://dune.com/queries/8916637
-- Matview: dune.paltalabs.result_scf_defindex_activity_archive   cron: 0 3 * * 1
-- Última ejecución: 01M4DYYYCT5JWNRXF6Q7NCZVR6 (build completo)
-- Costo: 2.239 cr; filas: 143653; engine medium
-- Generated by scripts/activity_sql.py. Archive, incremental: previous snapshot of this matview
-- plus, on the first Monday of the month only, the month that just closed.
WITH prev AS (SELECT * FROM dune.paltalabs.result_scf_defindex_activity_archive WHERE row_kind = 'activity'),
src AS (
SELECT 'defindex' AS protocol, e.vault AS contract_id, e.closed_at, lower(to_hex(e.tx_hash)) AS tx_hash,
  e."to" AS user_address, 'vault_' || e.event AS action, 'vault_depositor' AS role, e.vault AS pool,
  e.asset AS token_a, CAST(e.amount AS DECIMAL(38,7)) AS amount_a,
  CAST(NULL AS VARCHAR) AS token_b, CAST(NULL AS DECIMAL(38,7)) AS amount_b
FROM dune.paltalabs.result_de_findex_vaults_events e
WHERE CAST(e.closed_at AT TIME ZONE 'UTC' AS DATE) >= CURRENT_DATE - INTERVAL '75' DAY AND CAST(e.closed_at AT TIME ZONE 'UTC' AS DATE) >= (SELECT MAX(covered_until) FROM dune.paltalabs.result_scf_defindex_activity_archive WHERE row_kind = 'metadata') AND CAST(e.closed_at AT TIME ZONE 'UTC' AS DATE) < CAST(date_trunc('month', CURRENT_DATE) AS DATE) AND day_of_month(CURRENT_DATE) <= 7 AND e.event IN ('deposit', 'withdraw')
)
SELECT protocol, contract_id, closed_at, tx_hash, user_address, action, role, pool, token_a, amount_a, token_b, amount_b,
       'activity' AS row_kind, covered_from, CASE WHEN day_of_month(CURRENT_DATE) <= 7 THEN GREATEST((SELECT MAX(covered_until) FROM dune.paltalabs.result_scf_defindex_activity_archive WHERE row_kind = 'metadata'), CAST(date_trunc('month', CURRENT_DATE) AS DATE)) ELSE (SELECT MAX(covered_until) FROM dune.paltalabs.result_scf_defindex_activity_archive WHERE row_kind = 'metadata') END AS covered_until, refreshed_at, source_layer
FROM prev
UNION ALL
SELECT protocol, contract_id, closed_at, tx_hash, user_address, action, role, pool, token_a, amount_a, token_b, amount_b,
       'activity', DATE '2025-05-01', CASE WHEN day_of_month(CURRENT_DATE) <= 7 THEN GREATEST((SELECT MAX(covered_until) FROM dune.paltalabs.result_scf_defindex_activity_archive WHERE row_kind = 'metadata'), CAST(date_trunc('month', CURRENT_DATE) AS DATE)) ELSE (SELECT MAX(covered_until) FROM dune.paltalabs.result_scf_defindex_activity_archive WHERE row_kind = 'metadata') END, CURRENT_TIMESTAMP, 'archive'
FROM src
WHERE regexp_like(user_address, '^[GC][A-Z2-7]{55}$') AND role IS NOT NULL
UNION ALL
SELECT 'defindex', NULL, CAST(NULL AS TIMESTAMP WITH TIME ZONE), NULL, NULL, NULL, NULL, NULL, NULL, CAST(NULL AS DECIMAL(38,7)), NULL, CAST(NULL AS DECIMAL(38,7)),
       'metadata', DATE '2025-05-01', CASE WHEN day_of_month(CURRENT_DATE) <= 7 THEN GREATEST((SELECT MAX(covered_until) FROM dune.paltalabs.result_scf_defindex_activity_archive WHERE row_kind = 'metadata'), CAST(date_trunc('month', CURRENT_DATE) AS DATE)) ELSE (SELECT MAX(covered_until) FROM dune.paltalabs.result_scf_defindex_activity_archive WHERE row_kind = 'metadata') END, CURRENT_TIMESTAMP, 'archive'
