-- Query: https://dune.com/queries/8916639
-- Matview: dune.paltalabs.result_scf_defindex_activity   cron: 0 5 * * *
-- Última ejecución: 01M4DZ092VY88HZRJDPJDXQ5XR
-- Costo: 1.152 cr; filas: 7210; engine medium
-- Generated by scripts/activity_sql.py. Normalized activity, docs/modelo-de-datos.md.
-- live: one row per user action plus one metadata row with the covered range.
WITH src AS (
SELECT 'defindex' AS protocol, e.vault AS contract_id, e.closed_at, lower(to_hex(e.tx_hash)) AS tx_hash,
  e."to" AS user_address, 'vault_' || e.event AS action, 'vault_depositor' AS role, e.vault AS pool,
  e.asset AS token_a, CAST(e.amount AS DECIMAL(38,7)) AS amount_a,
  CAST(NULL AS VARCHAR) AS token_b, CAST(NULL AS DECIMAL(38,7)) AS amount_b
FROM dune.paltalabs.result_de_findex_vaults_events e
WHERE CAST(e.closed_at AT TIME ZONE 'UTC' AS DATE) >= CURRENT_DATE - INTERVAL '75' DAY AND CAST(e.closed_at AT TIME ZONE 'UTC' AS DATE) >= (SELECT MAX(covered_until) FROM dune.paltalabs.result_scf_defindex_activity_archive WHERE row_kind = 'metadata') AND CAST(e.closed_at AT TIME ZONE 'UTC' AS DATE) < CURRENT_DATE AND e.event IN ('deposit', 'withdraw')
)
SELECT protocol, contract_id, closed_at, tx_hash, user_address, action, role, pool, token_a, amount_a, token_b, amount_b,
       'activity' AS row_kind, GREATEST((SELECT MAX(covered_until) FROM dune.paltalabs.result_scf_defindex_activity_archive WHERE row_kind = 'metadata'), CAST(CURRENT_DATE - INTERVAL '75' DAY AS DATE)) AS covered_from, CURRENT_DATE AS covered_until,
       CURRENT_TIMESTAMP AS refreshed_at, 'live' AS source_layer
FROM src
WHERE regexp_like(user_address, '^[GC][A-Z2-7]{55}$') AND role IS NOT NULL
UNION ALL
SELECT 'defindex', NULL, CAST(NULL AS TIMESTAMP WITH TIME ZONE), NULL, NULL, NULL, NULL, NULL, NULL, CAST(NULL AS DECIMAL(38,7)), NULL, CAST(NULL AS DECIMAL(38,7)),
       'metadata', GREATEST((SELECT MAX(covered_until) FROM dune.paltalabs.result_scf_defindex_activity_archive WHERE row_kind = 'metadata'), CAST(CURRENT_DATE - INTERVAL '75' DAY AS DATE)), CURRENT_DATE, CURRENT_TIMESTAMP, 'live'
